
#android sdk for miui patchrom
export PATH=${PATH}:~/android-sdk-linux/tools
export PATH=${PATH}:~/android-sdk-linux/platform-tools

#CONFIGURE CCACHE FOR BUILDING ANDROID
export USE_CCACHE=1

#SET JAVA
unset _JAVA_OPTIONS

#SET REPO
export PATH=~/bin:$PATH

#CONFIGURE JACK FOR BUILDING ANDROID
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"
